platform :ios, '10.0'
use_frameworks!

target 'WeatherApp' do
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  target 'WeatherAppTests' do
      inherit! :search_paths
      pod 'OHHTTPStubs'
  end
end
